package com.android_alex_shtain_assignment

import com.android_alex_shtain_assignment.core.base.BaseActivity
import com.android_alex_shtain_assignment.databinding.ActivityMainBinding
import dagger.hilt.android.AndroidEntryPoint

@AndroidEntryPoint
class MainActivity : BaseActivity<ActivityMainBinding>(ActivityMainBinding::inflate)